Entity Registration Fix
WayofTime/BloodMagic pull request #1087
Opened 2017-03-07 23:28 UTC by majikguy

Replaced the Entity registration code. 

Before, the code was manually adding entities to the GameRegistry. Doing this prevents the engine from fully registering the added entities in all the proper places. The result was that the Client was never informed of when these entities were created or what they were doing, as all of that behavior is managed by the EntityRegistry.

Changing to the proper EntityRegistry calls fixes issue #1065.

It should be noted that I wasn't super sure what to enter as the values for the  tracking components for the entities, so I set all of them to send tracking updates to the player as long as they are within  4 chunks, send those tracking updates every 3 ticks, and to include velocity with the tracking data. If this should be changed later, it can be done in another pull request.
![2017-03-07_18 28 07](https://cloud.githubusercontent.com/assets/7277096/23682870/d8c26456-0363-11e7-8cf8-35bef5ffaaa1.png)

2017-03-07 23:31 UTC, TehNut requested changes

2017-03-07 23:31 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/registry/ModEntities.java
> +        EntityRegistry.registerModEntity(new ResourceLocation(Constants.Mod.MODID+":BloodLight"),EntityBloodLight.class, "BloodLight",++entities, BloodMagic.instance,16*4, 3, true);
Missing some whitespacing in these. Also, use the the RL constructor with 2 string inputs.

2017-03-07 23:47 UTC, majikguy commented
I have replaced the ResourceLocation calls with the two-argument version and added more consistent white-space.

2017-03-08 00:01 UTC, TehNut approved these changes

2017-03-08 00:02 UTC, TehNut commented
Just curious, is there any reason you're using `16*4` for each of these instead of 64?

2017-03-08 00:06 UTC, majikguy commented
Seems a bit more clear than just 64, since it makes it easier to understand that it is 4 chunks at a glance

2017-03-08 00:17 UTC, TehNut commented
Good enough of a reason for me ¯\\\_(ツ)_/¯

2017-03-08 00:17 UTC, merged