Reinstated Compression sigil.
WayofTime/BloodMagic pull request #1374
Opened 2018-07-24 04:46 UTC by Iorce

- does not compress wooden planks into crafting tables
- searches for reversible 3x3/2x2 recipes with a single material type
- probably has a lot of redundant stuff and looks silly
- uses try/catch (might want to find a different approach, some people scoff at this)
- should probably have spent the night sleeping, I'm taking exams tomorrow and will probably sleep the whole day through.

2018-07-24 05:07 UTC, TehNut requested changes

2018-07-24 05:07 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/AdvancedCompressionHandler.java
> +            if (invStack.isEmpty() || invStack.equals(ItemStack.EMPTY)) {
Needless additional check

2018-07-24 05:07 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/AdvancedCompressionHandler.java
> +                if (!stack.isEmpty() && !invStack.equals(ItemStack.EMPTY) && invStack != ItemStack.EMPTY) {
Needless additional checks

2018-07-24 05:07 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/AdvancedCompressionHandler.java
> +            if (invStack == null || invStack.isEmpty() || invStack.equals(ItemStack.EMPTY)) {
Needless additional checks

2018-07-24 05:07 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/AdvancedCompressionHandler.java
> +        try {
try/catch is slow. You should be properly nullchecking the recipe you get back.

2018-07-24 05:07 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/AdvancedCompressionHandler.java
> +        try{result = CraftingManager.findMatchingRecipe(inventory, world).getRecipeOutput();
Again, try/catch is slow. Properly check your result.

2018-07-24 05:07 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/BaseCompressionHandler.java
> +            if (invStack.isEmpty() || invStack.equals(ItemStack.EMPTY) || invStack == ItemStack.EMPTY) {
More needless checks

2018-07-24 05:07 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/CompressionRegistry.java
> +            if (stack != null && stack != ItemStack.EMPTY) {
`stack.isEmpty()`

2018-07-24 06:17 UTC, Iorce commented
Done.

2018-07-24 16:01 UTC, TehNut requested changes
Delete any commented code. VCS exists for a reason.

2018-07-24 16:01 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/AdvancedCompressionHandler.java
> +        if(CraftingManager.findMatchingRecipe(inventory, world) != null) {
Don't make this query twice. Store your result.

2018-07-24 16:01 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/AdvancedCompressionHandler.java
> +        if(CraftingManager.findMatchingRecipe(inventory, world) != null){
Same here

2018-07-24 16:01 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/AdvancedCompressionHandler.java
> +            StorageBlockCraftingManager.getInstance().addRecipe(CraftingManager.findMatchingRecipe(inventory, world));
Same here...

2018-08-07 22:40 UTC, TehNut requested changes

2018-08-07 22:40 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/AdvancedCompressionHandler.java
> +        InventoryCrafting inventory = new InventoryCrafting(new Container() {
This should be stored as a constant. No need to create a new instance each time this is called.

2018-08-07 22:40 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/AdvancedCompressionHandler.java
> +        InventoryCrafting inventory = new InventoryCrafting(new Container() {
To go with the above, maybe a `Cache<Point2i, InventoryCrafting>`?

2018-08-07 22:40 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/AdvancedCompressionHandler.java
> +    public static boolean has22Recipe(ItemStack stack, World world) {
Remove this. Anybody using this is being inefficient since they can just call `get22Recipe(...)` and check if it's empty themselves.

2018-08-07 22:40 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/AdvancedCompressionHandler.java
> +    public static boolean has33Recipe(ItemStack stack, World world) {
Remove this. Anybody using this is being inefficient since they can just call `get33Recipe(...)` and check if it's empty themselves.

2018-08-07 22:40 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/BaseCompressionHandler.java
> +
Extra line

2018-08-07 22:40 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/CompressionHandler.java
> +
Extra line

2018-08-07 22:40 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/BaseCompressionHandler.java
> +
Extra line

2018-08-07 22:40 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compress/CompressionRegistry.java
> +        /*for (Map.Entry<ItemStack, Integer> entry : thresholdMap.entrySet()) {
Delete

2018-08-18 01:11 UTC, TehNut commented
Is this tested on a server with multiple players compressing things?

2018-08-18 23:19 UTC, keraldi commented
Works if multiple players use it simultaneously but there's a dupe that creates i extra compressed items for 8*i +1 re-compressed items.

2018-08-19 18:31 UTC, Iorce commented
Done. Something about a function with different parameters returning different results.

2018-08-26 19:53 UTC, TehNut approved these changes

2018-08-26 20:05 UTC, TehNut commented
![image](https://user-images.githubusercontent.com/5789439/44632510-b1202b80-a930-11e8-9473-6516828b8084.png)

2018-08-26 20:05 UTC, merged