Several mimic fixes, with actually cleaned up commit history.
WayofTime/BloodMagic pull request #1379
Opened 2018-07-28 21:48 UTC by KohaiKhaos

In response to #1376
A few fixes to mimics have been made to restore the long-missing shift+right click behavior of mimic blocks when placed. Now they'll replace blocks when shift-clicked onto them, and will inherit the BlockState of blocks replaced in this way.

 - Reimplemented the shift+right click behavior of mimics and implemented an explicit mimic ItemBlock
 - Changed the mimic tile from using metadata to using blockstates when storing the replaced block's information. This includes edits to the block, tile, and entity files.
 - Copied parseState() from WayofTime.bloodmagic.api.impl.BloodMagicCorePlugin to a public function in a new class WayofTime.bloodmagic.util.Serializer, because TehNut told me to not put it in Utils.java
 - Completely removed the TileMimic#metaOfReplacedBlock variable and all calls to it. Mimics no longer use metadata directly for their replaced blocks, any metadata values are derived from blockstate.

Also this time I checked to make sure I didn't have a bunch of random extraneous commits and repeats of commits from this repo.

2018-07-31 15:52 UTC, Iorce commented on src/main/java/WayofTime/bloodmagic/entity/mob/EntityMimic.java
> +                //mimic.metaOfReplacedBlock = metaOfReplacedBlock;
Nut doesn't like commented code

-> VCS exists

2018-07-31 15:52 UTC, Iorce commented on src/main/java/WayofTime/bloodmagic/entity/mob/EntityMimic.java
> +        //this.metaOfReplacedBlock = metaOfReplacedBlock;
Nut doesn't like commented code

2018-07-31 15:52 UTC, Iorce commented on src/main/java/WayofTime/bloodmagic/item/block/ItemBlockMimic.java
> +    //Old: public EnumActionResult onItemUse(ItemStack stack, EntityPlayer player, EnumHand hand, World world, BlockPos pos, EnumFacing facing, float hitX, float hitY, float hitZ)
Nut doesn't like commented code

2018-07-31 15:53 UTC, Iorce commented on src/main/java/WayofTime/bloodmagic/tile/TileMimic.java
> +        //metaOfReplacedBlock = tag.getInteger("metaOfReplacedBlock");
Nut doesn't like commented code

2018-07-31 15:53 UTC, Iorce commented on src/main/java/WayofTime/bloodmagic/tile/TileMimic.java
> +        //tag.setInteger("metaOfReplacedBlock", metaOfReplacedBlock);
Nut doesn't like commented code

2018-07-31 23:10 UTC, KohaiKhaos commented
Cleaned up the bits of commented out code I missed.

2018-08-01 00:11 UTC, TehNut requested changes
This should be formatted with spaces, not tabs.

While you're at it, remove the usage of the old copy of the state deserialization and point it's usage at the new util.

2018-08-01 00:11 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/entity/mob/EntityMimic.java
> +    public boolean dropItemsOnBreak = true/
?

2018-08-01 00:11 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/util/Serializer.java
> +public class Serializer
`StateUtil`

2018-08-01 00:41 UTC, KohaiKhaos commented
I am the dumb. Especially for not noticing too well that the BM files use spaces rather than tabs to indent.
I am now the guy who decides to mix spaces and tabs for indentation. Angering all.

2018-08-01 12:01 UTC, Iorce commented
Every decent IDE should have a setting that automatically converts tabs to spaces when tabbing.

2018-08-07 22:43 UTC, TehNut requested changes

2018-08-07 22:43 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/entity/mob/EntityMimic.java
> +    this.stateOfReplacedBlock = stateOfReplacedBlock;
Spacing

2018-08-07 22:43 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/entity/mob/EntityMimic.java
> +        mimic.setReplacedState(this.stateOfReplacedBlock);
Spacing

2018-08-07 22:43 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/tile/TileMimic.java
> +    mimicedTile = getTileFromStackWithTag(getWorld(), pos, getStackInSlot(0), tileTag, stateOfReplacedBlock);
Spacing

2018-08-07 22:43 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/tile/TileMimic.java
> +    tag.setString("stateOfReplacedBlock",stateOfReplacedBlock.toString());
Spacing

2018-08-07 23:28 UTC, merged