Teleposition crossdimension (requires copyright permission from brandon3055)
WayofTime/BloodMagic pull request #1385
Opened 2018-08-03 01:10 UTC by Iorce

DO NOT USE. REQUIRES COPYRIGHT PERMISSION FROM BRANDON3055 (CURRENTLY AWAITING RESPONSE / UNTIL THEN PRIVATE USE ONLY).

Request query has been sent to brandon3055 through curseforge. Awaiting response.
Will attach screenshot of the conversation in case there is a positive result, else delete this branch / close pull request.

2018-08-03 01:35 UTC, TehNut commented
You realize his license permits this already, right?

2018-08-03 04:02 UTC, Iorce commented
Finished. Please review. Performance improvements might be possible.

2018-08-07 22:51 UTC, TehNut requested changes

2018-08-07 22:51 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/ritual/portal/Teleports.java
> +                                if (MinecraftForge.EVENT_BUS.post(new TeleposeEvent.Ent(entity, entity.getEntityWorld(), entity.getPosition(), newWorldServer, targetTeleposer))) {
```java
if (teleposer && MinecraftForge.EVENT_BUS.post(new TeleposeEvent.Ent(entity, entity.getEntityWorld(), entity.getPosition(), newWorldServer, targetTeleposer))
```

2018-08-07 22:51 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/ritual/portal/Teleports.java
> +                            ForgeChunkManager.releaseTicket(chunkTicket);
The ticket is only being released when a player is being teleported. Any other mob will retain the ticket.

2018-08-08 00:47 UTC, Iorce commented
Done.

2018-08-08 00:50 UTC, TehNut approved these changes

2018-08-08 00:50 UTC, merged

2018-08-08 02:00 UTC, MentalMouse commented
Doesn't the teleposer swap source and destination?  That might be awkward with unloaded chunks.

2018-08-08 02:15 UTC, TehNut commented
This loads the chunk if it's unloaded