Ritual portal delay / Bound Pickaxe fix/improvement
WayofTime/BloodMagic pull request #1387
Opened 2018-08-03 14:34 UTC by Iorce

RitualPortal (Gate of the Fold) now works similar to the Nether Portal in respect of teleportation cooldown (you have to leave the portal first). This also affects teleposers (if a teleportation within 10 ticks of the previous teleportation is attempted, nothing happens).

Bound Pickaxe now destroys blocks properly with removedByPlayer(), this triggers a block update and everything that happens if a player destroys a block in creative mode (Drops are put directly into the players inventory through a function that is executed before the block removal).

this closes #1001

2018-08-07 22:54 UTC, TehNut requested changes

2018-08-07 22:54 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/item/ItemBoundTool.java
> +        boolean silkTouch = EnchantmentHelper.getEnchantmentLevel(Enchantments.SILK_TOUCH, stack) > 0;
Silk Touch and Fortune levels should be passed in as arguments. The levels won't be changed between each block check.

2018-08-08 08:37 UTC, Iorce commented
I should have known better. For some reason I thought having less imports and not passing it is better, completly ignoring that it would be inside of 3 for-loops for every tool.

2018-08-26 19:49 UTC, TehNut approved these changes

2018-08-26 19:50 UTC, merged