Fix: Interaction Sigil of Holding + Seer/Divination Sigil (no render)
WayofTime/BloodMagic pull request #1391
Opened 2018-08-06 15:36 UTC by Iorce

Seer Sigil and Sigil of Divination now work properly when placed inside the Sigil of Holding
(rendering not included)

closes #1285

2018-08-07 23:02 UTC, TehNut requested changes

2018-08-07 23:02 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/client/hud/element/ElementDivinedInformation.java
> +                flag = isFlagSigilHolding(sigilStack, true);
Move this to the if block above to make the logic flow clearer

2018-08-07 23:02 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/client/hud/element/ElementDivinedInformation.java
> +                flag = isFlagSigilHolding(sigilStack, false);
Move this to the if block above to make the logic flow clearer

2018-08-08 08:16 UTC, Iorce commented
Done.

2018-08-18 01:13 UTC, merged