Phantom bridge
WayofTime/BloodMagic pull request #1397
Opened 2018-08-09 15:11 UTC by Iorce

Rework.
Diagonally doesn't work properly yet, some variables are switched up which is why the template doesn't work properly.
Rest works and should work better than before.
Just cannot go speeding diagonally.

2018-08-12 06:05 UTC, Iorce commented
~ finished please review ~

2018-08-12 06:16 UTC, TehNut requested changes
Initial pass. I'm too tired to actually go over the logic right now.

I'm not a huge fan of all those 1 line helper methods.

2018-08-12 06:16 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/item/sigil/ItemSigilPhantomBridge.java
> +    public static final String[] circle7x7 = new String[]{
Constants should be `CONSTANT_CASE` and should appear at the top of the class.

2018-08-12 06:16 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/item/sigil/ItemSigilPhantomBridge.java
> +    public static boolean isPhantomActive(EntityPlayer entity) {
Static methods should appear below all member methods.

2018-08-12 06:16 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/item/sigil/ItemSigilPhantomBridge.java
> +    public static final String[] circle9x9 = new String[]{
Constants should be `CONSTANT_CASE` and should appear at the top of the class.

2018-08-12 06:16 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/item/sigil/ItemSigilPhantomBridge.java
> +    public static final String[] diagXZ = new String[] {
Constants should be `CONSTANT_CASE` and should appear at the top of the class.

2018-08-12 06:16 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/item/sigil/ItemSigilPhantomBridge.java
> +            if (-0.3 < playerVelZ && playerVelZ < 0.3) {
This reads very strangely. It should be `playerVelZ > -0.3 && playerVelZ < 0.3`. I understand you're trying to show a range, but it just makes it more confusing.

Same for all the other ranges done this way.

2018-08-12 06:16 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/item/sigil/ItemSigilPhantomBridge.java
> +            else //diagonal movement
This should have braces. It should also be on the same line as the brace above.

2018-08-12 06:16 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/item/sigil/ItemSigilPhantomBridge.java
> +        } else //anything between the first case and being slightly faster than walking
This needs a brace.

2018-08-12 06:16 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/item/sigil/ItemSigilPhantomBridge.java
> +                if(inverted && !XnZ || XnZ && !inverted) j--;
Newlines for this ifelse

2018-08-12 07:52 UTC, Iorce commented
Done.

2018-08-12 08:01 UTC, Iorce commented
Alternative explaination: I wanted more code.

2018-08-18 01:14 UTC, TehNut commented
My brain is too fried to try and understand this. If this doesn't work, you're toast.

2018-08-18 01:14 UTC, TehNut approved these changes

2018-08-18 01:14 UTC, merged