Reverence of the Condor port
WayofTime/BloodMagic pull request #1490
Opened 2018-12-30 23:42 UTC by Iorce

Added a small continous cost of `Blockvolume \ 10000 * playerCount`, the `playerCount` variable was always there was no cost. 

Using an AreaDescriptor, the area should be able to be modified. I defined the max. area as 100 horizontal and 200 vertical. Hence the cost based on block volume.

2018-12-30 23:50 UTC, TehNut requested changes

2018-12-30 23:50 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/ritual/types/RitualCondor.java
> +        System.out.println(aabb);
pls

2018-12-31 00:01 UTC, Iorce commented on src/main/java/WayofTime/bloodmagic/ritual/types/RitualCondor.java
> +        System.out.println(aabb);
OUPS.

2018-12-31 00:03 UTC, TehNut approved these changes

2018-12-31 00:13 UTC, merged