Ported Ritual of the Feathered Earth to BM2.
WayofTime/BloodMagic pull request #1492
Opened 2018-12-31 15:47 UTC by Iorce

2019-01-20 22:54 UTC, TehNut commented
I feel like a more user-friendly implementation of this would be to handle the actual effect in a damage event and cancelling it if it's fall damage while they're in range.

This current implementation is just constantly setting fall damage to 0 every second, even for entities which aren't moving, which just seems wong.

2019-01-23 15:57 UTC, Iorce commented
Done.

2019-02-01 00:27 UTC, TehNut requested changes

2019-02-01 00:27 UTC, TehNut commented on gradle.properties
> +forge_version=14.23.5.2768
Is this necessary?

2019-02-01 00:28 UTC, keraldi commented on gradle.properties
> +forge_version=14.23.5.2768
My bad.

2019-02-01 00:29 UTC, TehNut approved these changes

2019-02-01 00:29 UTC, merged