Mark of the Falling Tower meteor costs are now configurable
WayofTime/BloodMagic pull request #1518
Opened 2019-01-18 19:21 UTC by Iorce

via an additonal field "cost" in the .json config files

 if BM is updated from an old version, this would require meteor configuration to be regenerated or costs to be added manually; meteors would be for free (LP-wise) otherwise.

 These are the new default costs:
 IRON: 1,000,000 (same as before)
 GOLD: 2,500,000
 DIAMOND: 5,000,000 (requires Archmage Blood Orb)

2019-01-18 19:25 UTC, Iorce commented
#1475

2019-01-19 01:28 UTC, noobanidus commented
ilu

2019-01-19 01:42 UTC, TehNut requested changes

2019-01-19 01:42 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/item/ItemBoundTool.java
> +                    NonNullList<ItemStack> itemDrops = NonNullList.create();
Irrelevant change I'll do this myself.

2019-01-19 01:42 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/meteor/Meteor.java
> +        this.cost = 1000000;
GSON initializes classes with reflection and not the constructor. The default definition should be set at the field declaration.

2019-01-20 23:19 UTC, TehNut approved these changes

2019-01-20 23:20 UTC, merged