Make Movement & Updraft arrays stronger by adding more of their ingredients!
WayofTime/BloodMagic pull request #1520
Opened 2019-01-18 23:01 UTC by Iorce

Reduced base motion for Movement & Updraft arrays

2019-01-20 23:23 UTC, TehNut requested changes

2019-01-20 23:23 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/block/BlockAlchemyArray.java
> +                    if (stack.getItem() == playerItem.getItem()) {
```suggestion
                    if (ItemStack.areItemsEqual(stack, playerItem)) {
```

2019-01-20 23:23 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/alchemyArray/AlchemyArrayEffectUpdraft.java
> +        entity.motionY = motionY + motionYGlowstoneMod * (tileArray.getStackInSlot(0).getCount() - 1) + motionYFeatherMod * (tileArray.getStackInSlot(1).getCount() - 1);
This line is a bit long, do the math on another line like in the movement array.

2019-01-20 23:40 UTC, Iorce commented
Done.

2019-02-01 00:21 UTC, TehNut approved these changes

2019-02-01 00:22 UTC, merged