Ritual Reader Quality of Life
WayofTime/BloodMagic pull request #1528
Opened 2019-01-22 19:10 UTC by Iorce

Now returns proper errors.
Added `getCurrentRitual()` to `IMasterRitualStone`
RitualReader/RitualTinkerer can only select MRS with set Ritual.
If no range has been previously selected, a simple right click is enough to select an MRS.

2019-01-23 15:13 UTC, Iorce commented
#1524

2019-02-01 00:21 UTC, TehNut requested changes

2019-02-01 00:21 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/ritual/IMasterRitualStone.java
> +    int setBlockRangeByBounds(EntityPlayer player, String range, BlockPos offset1, BlockPos offset2);
Add a javadoc explaining what this int should be. However, it would probably be better to use an enum since those are fairly self-documenting.

2019-02-01 00:21 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/tile/TileMasterRitualStone.java
> +        switch (this.currentRitual.canBlockRangeBeModified(range, descriptor, this, offset1, offset2, holder)) {
pls

```java
int modificationType = currentRitual.canBlockRangeBeModified(...);
if (modificationType == 1)
    descriptor.modifyAreaByBlockPositions(offset1, offset2);

return modificationType;
```

2019-02-01 00:57 UTC, Iorce commented
Done

2019-02-01 01:11 UTC, TehNut approved these changes

2019-02-01 01:11 UTC, merged