Update zh_CN.lang
WayofTime/BloodMagic pull request #1655
Opened 2019-09-10 05:57 UTC by qianzha

I found that there is a missing key "ritual.bloodmagic.groundingRitual.groundingRange.info" at us_en.lang.

And these keys below are been setted twice with same value:
ritual.bloodmagic.condorRitual.info=Provides flight in an area around the ritual.
(at 679 line & 767 line)
ritual.bloodmagic.eternalSoulRitual.info=Capable of transferring Life Essence from a Network back into an Altar at a cost.
(at 680 line & 768 line)

2019-09-10 16:35 UTC, qianzha commented
>  Got tired of making one of these primitive buildings to generate cobblestone? Got tired of having OSHA on you or accidentally extinguishing your lava source? 

(Introduction of Cobblestone Ritual at guide book)
What does OSHA mean here?

2019-09-10 16:40 UTC, Iorce commented
OSHA is a US institution that regulates or enforces work safety laws.
https://en.wikipedia.org/wiki/Occupational_Safety_and_Health_Administration

In this context it's joking about lava sources being very dangerous and OSHA hunting the player down because lava is not safe to work with.

2019-09-10 17:02 UTC, qianzha commented
> OSHA is a US institution that regulates or enforces work safety laws.
> https://en.wikipedia.org/wiki/Occupational_Safety_and_Health_Administration
> 
> In this context it's joking about lava sources being very dangerous and OSHA hunting the player down because lava is not safe to work with.

Got it,  thx!

2019-09-18 12:32 UTC, qianzha commented
@3TUSK I just updated the zh_cn.lang of the guide book, which you did a large of translation of. Would you like to check it?

2019-09-19 05:27 UTC, 3TUSK requested changes
I was summoned.

2019-09-19 05:27 UTC, 3TUSK commented on src/main/resources/assets/bloodmagicguide/lang/zh_CN.lang
> +guide.bloodmagic.entry.ritual.forsakenSoul.info=##REQ-LORE##\n\t孤魂集会能加快仪式上方（默认下）的恶魔意志晶簇的生长。然而它并不能凭空生成意志，且晶簇的生长仍然需要恶魔结晶坛。运用机械师所识——生物具有“独特性”，要使晶簇更有效率的生长，就需要更多种类的生物死亡。同时，然而它也不能凭空生成恶魔意志灵域，所以你需要把意志晶体回馈于大气
`运用机械师所识——生物具有“独特性”`
->
`运用生物”独特性“这一机制`

2019-09-19 05:45 UTC, qianzha commented on src/main/resources/assets/bloodmagicguide/lang/zh_CN.lang
> +guide.bloodmagic.entry.ritual.forsakenSoul.info=##REQ-LORE##\n\t孤魂集会能加快仪式上方（默认下）的恶魔意志晶簇的生长。然而它并不能凭空生成意志，且晶簇的生长仍然需要恶魔结晶坛。运用机械师所识——生物具有“独特性”，要使晶簇更有效率的生长，就需要更多种类的生物死亡。同时，然而它也不能凭空生成恶魔意志灵域，所以你需要把意志晶体回馈于大气
Okay, it has been changed.

2019-09-19 05:50 UTC, qianzha commented on src/main/resources/assets/bloodmagicguide/lang/zh_CN.lang
> +guide.bloodmagic.entry.ritual.forsakenSoul.info=##REQ-LORE##\n\t孤魂集会能加快仪式上方（默认下）的恶魔意志晶簇的生长。然而它并不能凭空生成意志，且晶簇的生长仍然需要恶魔结晶坛。运用机械师所识——生物具有“独特性”，要使晶簇更有效率的生长，就需要更多种类的生物死亡。同时，然而它也不能凭空生成恶魔意志灵域，所以你需要把意志晶体回馈于大气
Are there any other problems?

2019-09-19 09:11 UTC, 3TUSK approved these changes

2019-09-19 09:11 UTC, 3TUSK commented on src/main/resources/assets/bloodmagicguide/lang/zh_CN.lang
> +guide.bloodmagic.entry.ritual.forsakenSoul.info=##REQ-LORE##\n\t孤魂集会能加快仪式上方（默认下）的恶魔意志晶簇的生长。然而它并不能凭空生成意志，且晶簇的生长仍然需要恶魔结晶坛。运用机械师所识——生物具有“独特性”，要使晶簇更有效率的生长，就需要更多种类的生物死亡。同时，然而它也不能凭空生成恶魔意志灵域，所以你需要把意志晶体回馈于大气
Nope.

2019-09-19 10:20 UTC, qianzha commented
@TehNut It's ready to be merged.

2020-12-30 19:44 UTC, merged