Added Gilded Living Armour Upgrade
WayofTime/BloodMagic pull request #1926
Opened 2022-08-28 20:52 UTC by VT-14

Gilded makes the Piglins found across the Nether passive, as if you were wearing a piece of Gold Armor.

Without this upgrade, Piglins are hostile, and appeasing them by wearing a piece of Gold Armor means you aren't wearing a full set of Living Armour, so you don't get the buffs.

Current Stats: Costs 5 Upgrade Points.  Crafted using a Binding Array and a Block of Gold.

This includes documentation in the Sanguine Scientiem.

2022-10-14 19:14 UTC, Keraldi requested changes

2022-10-14 19:14 UTC, keraldi commented on src/main/java/wayoftime/bloodmagic/common/item/ItemLivingArmor.java
> +			return false;
Redundant conditional branch at the end of function (remove `else return false` if a function/method closes afterwards)

2022-10-14 19:14 UTC, keraldi commented on src/main/java/wayoftime/bloodmagic/common/item/ItemLivingArmor.java
> +	@Override
Fairly sure that the `@Override` decorator is wrong here. If `makePiglinsNeutral()` does not exist in any super/parent class (not inherited), remove this line

2023-08-25 17:52 UTC, closed without merging

2023-08-25 17:52 UTC, VT-14 commented
Closing this in favor of #1968 (updated for 1.20).