Implement a functioning Blood Tank
WayofTime/BloodMagic pull request #969
Opened 2016-11-08 20:51 UTC by Arcaratus

-Added a search bar to the Upgrade Tomes Creative Tab
-Updated some Altar fluid code (remove deprecated stuff)
-Moved Rendering classes into appropriate package
-Fix the localization errors on the Demon Crystals
-A few cleanups here and there

-- TO DO --
-Add recipes for the Blood Tank
-Fix the lighting-not-updating-upon-fluid-placement within the tank bug
-Render tank in inventory if possible
-Future (maybe 1.11) update from deprecated methods and classes throughout entire mod

2016-11-08 21:12 UTC, TehNut commented
Again, please no TESR. Use the model system.

I will look over this more when I get home

2016-11-08 21:58 UTC, TehNut requested changes

2016-11-08 21:58 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compat/waila/provider/DataProviderBloodTank.java
> +        if (accessor.getPlayer().isSneaking() || config.getConfig(Constants.Compat.WAILA_CONFIG_BYPASS_SNEAK))
This whole bit is wrong. You cannot access a Tiles NBT here. Write everything you need to the tag in `#getNBTData` and read it from `accessor#getNBTData`. I need to fix our other implementations to do this. See the altar impl for an example.

2016-11-08 21:58 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/item/block/ItemBlockBloodTank.java
> +        setMaxDamage(0);
Unecessary.

2016-11-08 22:00 UTC, TehNut requested changes

2016-11-08 22:00 UTC, TehNut commented on src/main/resources/assets/bloodmagic/lang/en_US.lang
If you change this here, you need to change every language.

2016-11-09 00:06 UTC, TehNut approved these changes

2016-11-09 00:59 UTC, WayofTime commented
Good to pull, or need more stuff?

2016-11-09 01:47 UTC, TehNut commented
Needs tank rewritten as a model instead of a TESR

2016-11-10 17:26 UTC, WayofTime commented
@TehNut Talked to both Grum and cpw. They said that a TESR for any form of block that updates its model regularly is a bad idea because it redraws the chunk of 16^3 blocks that it is in. So the static part of the model (the block) should be a model, but the fluid part should either be a regular TESR or a fast TESR.

2016-11-10 17:31 UTC, TehNut commented
Alright, let's do that, then.

2016-11-11 01:49 UTC, TehNut commented on src/main/resources/assets/bloodmagic/blockstates/BlockBloodTank.json
> +	      "all": "bloodmagic:blocks/BloodTank"
If you add 

```json
"textures": {
    "all": "bloodmagic:blocks/BloodTank"
}
```

to the `"default": {}` block, you shouldn't need it in all of these variants.

2016-11-11 01:54 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compat/waila/provider/DataProviderBloodTank.java
> +                if (!Strings.isNullOrEmpty(tag.getString("FluidName")) && FluidStack.loadFluidStackFromNBT(tag) != null)
Save the `FluidStack` instead of creating it from NBT twice.

2016-11-11 01:57 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compat/waila/provider/DataProviderBloodTank.java
> +                    currenttip.add(TextHelper.localizeEffect("tooltip.BloodMagic.fluid.amount") + ": " + tag.getInteger("Amount") + "/" + bloodTank.getCapacity() + "mB");
This `getCapacity()` call (and the one above) need to either be changed to be retrieved from NBT or the `getCapacity()` method needs to be changed to not depend on a field obtained via NBT.

2016-11-11 01:58 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/client/render/block/RenderBloodTank.java
> +    public static TextureAtlasSprite checkIcon(TextureAtlasSprite icon)
Why create this method? You run this bit of code once, as far as I can tell.

2016-11-11 02:00 UTC, TehNut commented
Whitespacing seems to be a mix of tabs and spaces. Please convert all of the tabs to spaces.

2016-11-11 02:02 UTC, WayofTime commented
That said, I'll probably be running Eclipse's formatter afterwards, so the last part isn't as bad of an issue.

2016-12-03 01:56 UTC, TehNut requested changes

2016-12-03 01:56 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/compat/jei/BloodMagicPlugin.java
> +    public void onRuntimeAvailable(IJeiRuntime runtime)
Why implement this? `BlankModPlugin` should be taking care of any unneeded methods.

2016-12-03 01:56 UTC, TehNut commented on src/main/java/WayofTime/bloodmagic/util/handler/event/BakedCustomItemModel.java
> + * https://github.com/aidancbrady/Mekanism
`@author aidancbrady`

2016-12-03 02:34 UTC, TehNut approved these changes

2016-12-12 01:28 UTC, merged